site_name: OCRed

theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Saira

extra_css:
  - stylesheets/extra.css

strict: false

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      theme: dark

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

docs_dir: docs

nav:
  - Home: "index.md"
  - Installation: "install.md"
  # - Examples:
  - Reference: "reference.md"
  - Contributing: "contributing.md"
  - Changelog: "changelog.md"
  - Code of Conduct: "conduct.md"
